/* eslint-disable */
// This file is auto-generated by @tanstack/router-vite-plugin on dev/build.
// Committed as a placeholder so the initial install + typecheck succeeds before
// the plugin runs for the first time. It will be overwritten on the next dev/build.

import { rootRouteWithContext } from '@tanstack/react-router';

const placeholder = rootRouteWithContext()({});
export const routeTree = placeholder;
