/**
 * Status of a single card within a variant fetch operation.
 */
export type TCardFetchStatus = 'pending' | 'done' | 'failed';

/**
 * In-memory progress record for a variant fetch operation.
 *
 * Keyed by deckId in the VariantFetchService progress Map so that
 * GET /decks/:deckId can look up progress without needing the fetchId.
 *
 * fetchId is still generated per startFetch call and returned to the
 * POST caller for client-side correlation.
 */
export interface IVariantFetchProgress {
  /** UUID generated by crypto.randomUUID() at startFetch time. */
  readonly fetchId: string;

  /** Total number of cards to fetch. */
  readonly total: number;

  /** Number of cards that completed successfully. */
  completed: number;

  /** Number of cards that failed (network or parse error). */
  failed: number;

  /** True while the async orchestration loop is still running. */
  inProgress: boolean;

  /** Wall-clock time the fetch was started. */
  readonly startedAt: Date;

  /**
   * Per-card status map keyed by cardIdentifier.
   * Mutable to allow updates as each card completes.
   */
  readonly cards: Map<string, TCardFetchStatus>;

  /**
   * True if the orchestration loop encountered an unrecoverable error
   * (e.g., DB connection drop). Distinct from per-card failures.
   * When true, inProgress will also be false (set in the finally block).
   */
  globalFailed: boolean;
}
